### ISSUE TITLE
Alternate Fizzbuzz gives unexpected results

### ISSUE THREAD

**Issue by Earthmark** [dbaumgarten/yodk#1]
I preface this with I'm new to yolol, but I believe this should still work just as your version of fizzbuzz does.

Exec built from commit f985b76869b0582dcc4a1ea18ef5ee3d64b7b72e

Yolol program in question
```
:out="" :iter=20 a=0
if a>:iter then goto 9 end
if a!=0 then :out+=" " end
b=""
if a%3==0 then b+="fizz" end
if a%5==0 then b+="buzz" end
if b=="" then :out+=a else :out+=b end
a++ goto 2
```

Expected the output once execution is done:
```
:iter 20
:out 'fizzbuzz 1 2 fizz 4 buzz fizz 7 8 fizz buzz 11 fizz 13 14 fizzbuzz 16 17 fizz 19 buzz'
a 21
b 'buzz'
```

Actual output
```
:iter 20
:out '0fizzbuzz 1 2 3fizz 4 5buzz 6fizz 7 8 9fizz 10buzz 11 12fizz 13 14 15fizzbuzz 16 17 18fizz 19 20buzz'
a 21
b 'buzz'
```

It seems like the first part of the else case is being run even if the if is false, if I try to in debug mode with breakpoints it starts having unexpected behaviors. For instance if I put a breakpoint at line 3 the second time the breakpoint is hit I get an error,
`Runtime error at Line: 3, Coloumn: 4 (up to Line: 3, Coloumn: 5): Variable a used before assignment`
If I put a breakpoint at 4 then only b is defined on the second iteration and the error never comes up. Also, trying to print the variables quite often doesn't print any variables at all.
I'll start poking around the code as well to try to understand what is happening, but I figure I should let you know first in case this is a known issue or some such.

Thanks for making a fun tool to play with!

**Comment by dbaumgarten** [comment]
Hi, thank you for trying out yodk. 
I have fixed the bug in the parser that lead to the unexpected output, you were correct, the first statement of the if-block was also executed during the else-block.

The breakpoints/stepping for the debugging of yolol code seem to be broken currently. It seems like trying to add nolol-support to the debugger in 304e8d64857bc94cd broke some things.
I am working on fixing it.

Thank you for finding these bugs.

**Comment by dbaumgarten** [comment]
This one was interesting. 
I guess you tried continuing from the breakpoint by typing r/run?
Typing r restarts the VM and because of a small error in the parser, reusing an instance of the parser (which the vm did when restarting) resulted in a parsed program with 0 lines, which leads to unexpected behavior if you expect to find more then 0 lines.

I fixed this now by:
- making the parser re-usable
- displaying a (y/n) prompt when trying to restart a running vm (and giving a hint that you may want to use continue/c instead

Your program should now work as expected. If so, please close this issue.
If you find any other bugs (there sure are many) let me know.

**Comment by Earthmark** [comment]
I haven't had time to validate this yet, I'll be able to later today and I'll get the issue updated or closed as applicable

**Comment by Earthmark** [comment]
Program now emits the expected output as 
```
:iter 20
:out 'fizzbuzz 1 2 fizz 4 buzz fizz 7 8 fizz buzz 11 fizz 13 14 fizzbuzz 16 17 fizz 19 buzz'
a 21
b 'buzz'
```
Thank you!
Also, as you reported, debugging is fixed as well.

Thank you for the quick fixes!
