### ISSUE TITLE
Gotos without a space should be recognized as valid syntax

### ISSUE THREAD

**Issue by CrankyCorvids** [dbaumgarten/yodk#34]
In the game, a goto functions identically whether it is written as "goto 1" or "goto1", but the latter is not recognized as valid by Yodk. Since the latter is sometimes preferable for line length optimization reasons, it would be better to recognize it as valid and take advantage of it when doing optimization.

**Comment by dbaumgarten** [comment]
Hi,
thank you for opening an issue.

The thing is, yolol is even stranger than you think. As it turns out, you can leave out most of the spaces, not only the one inside the goto.

I think that's more a bug than a feature and should be fixed by Frozenbyte. That's why I am hesitating to "officially" support this madness.

One possibility would be to have the no-spaces-madness-mode as an opt-in feature (via cli-flags and vscode settings), so people who really want it can use it and everyone else does not have to deal with it.

I actually did some first steps into this direction today, so I might come up with a solution in the next few days.

**Comment by dbaumgarten** [comment]
So, I just released v0.0.20 and starting from this version most spaces are no longer required.
This means "goto1" will now be valid (along with lots of other stuff) and "yodk optimize" and "yodk compile" will by default output code with as little spaces as possible.
