### ISSUE TITLE
"Cannot execute binary file" error when starting the VS Code extension on Mac.

### ISSUE THREAD

**Issue by Lumi-Virtual** [dbaumgarten/yodk#38]
/Users/[User]/.vscode/extensions/dbaumgarten.vscode-yolol-0.0.30/bin/yodk: /Users/[User]/.vscode/extensions/dbaumgarten.vscode-yolol-0.0.30/bin/yodk: cannot execute binary file
[Info  - 12:36:07 PM] Connection to server got closed. Server will restart.

This message happens 5 times then VS Code gives up trying to run it.

Seems like this causes everything except basic syntax highlighting to not work.

I'm on macOS Mojave 10.14.6 (18G7016) on x86-64 architecture.

**Comment by dbaumgarten** [comment]
Well, that's not a bug, it's a (missing) feature.

Most of the functionality is provided by a binary written in go. Because of this, the extension needs to include a binary for every supported architecture. And at the moment it simply includes no binary for MacOS.

I could add a binary for MacOS, but without having a Mac to test it, chances are big that random things just don't work. (Which is the reason why I haven't already done it)

**Comment by Lumi-Virtual** [comment]
Ah fair. What would be involved in making one? I might be able to do so with a bit of direction.

**Comment by dbaumgarten** [comment]
I have created an experimental release with macOS support. All you would have to do is try it out and report any errors you encounter.
You can find it [here](https://github.com/dbaumgarten/yodk/releases/tag/macostest.)
Download and install the vsix-file (you will have to uninstall the version you installed from the marketplace first).

**Comment by Lumi-Virtual** [comment]
Oh excellent alright! I'll be sure to report any bugs, but it seems to be working fine!

**Comment by dbaumgarten** [comment]
I have just released v0.0.31, which includes MacOS-Support. This means you can uninstall your test-version and install the extension from the marketplace. This way you will automatically receive future updates.
