### ISSUE TITLE
C-style multi-line commenting in NOLOL

### ISSUE THREAD

**Issue by Woccz** [dbaumgarten/yodk#43]
A multi-line comment would be really helpful.
It makes logical sense to use `/* Comment */`, to fit with the C style `//` comments.

Thank you.

**Comment by dbaumgarten** [comment]
I guess there are use-cases for this. But there isn't really anything "/* */" can to which "// " can't. Especially when using vscode's shortcuts to comment out whole blocks. (Highlight code with mouse, press CTRL+K+C to comment-out the highlighted code and CTRL+K+U to undo commenting).

But I guess this comes down to personal preferences.

I will look into it. If it is easy enough to add, I will do so. If it turns out to be a lot more work than it's worth, I'd rather not.

**Comment by Woccz** [comment]
Ok. Feel free to close the issue if you decide not to implement it.

**Comment by dbaumgarten** [comment]
I looked into this.
The problem here is, that comments are just regarded as part of line (even if there isn't anything else on that line).
Having comments span multiple lines just doesn't fit this.
It would require a lot of changes and would probably introduce a bunch of very subtle bugs.
So in the end I think the added benefit is simply not worth the effort.

**Comment by Woccz** [comment]
The CTRL+K+C style commenting works fine, however, can't you just use a really simple function to remove all `/* */` comments pre-processing?
For example in Python:
```python
while '/*' in code:
    code = code[:code.find('/*')]+code[code.find('*/')+2:]
```
removes all multi-line comments? (barring nested block-comments, which could be relatively easily fixed)

Or are you dealing with a different problem?


Thank you.

**Comment by dbaumgarten** [comment]
Simply removing it would be dead simple.
But that would make the comment simply disappear when trying to Auto-Format the code.
Comments have to be properly included in the AST so they can be added back when converting the AST back to code.
That's what makes this difficult.
